export const corgiData = [
    {
        emotionTags: ["moody", "hungry"],
        isGif: true,
        image: "angry.gif",
        alt: "A corgi looking moody",
    },
    {
        emotionTags: ["moody"],
        isGif: true,
        image: "angry1.gif",
        alt: "A corgi looking moody",
    },
    {
        emotionTags: ["confused"],
        isGif: true,
        image: "confused.gif",
        alt: "A corgi looking confused",
    },
    {
        emotionTags: ["confused"],
        isGif: false,
        image: "confused.jpg",
        alt: "A corgi looking confused",
    },
    {
        emotionTags: ["confused", "scared"],
        isGif: true,
        image: "confused1.gif",
        alt: "A corgi looking confused",
    },
    {
        emotionTags: ["confused"],
        isGif: true,
        image: "confused2.gif",
        alt: "A corgi looking confused",
    },
    {
        emotionTags: ["confused"],
        isGif: true,
        image: "confused3.gif",
        alt: "A corgi looking confused",
    },
    {
        emotionTags: ["dominant"],
        isGif: true,
        image: "cool.gif",
        alt: "A corgi looking dominant",
    },
    {
        emotionTags: ["dominant"],
        isGif: false,
        image: "cool.jpg",
        alt: "A corgi looking dominant",
    },
    {
        emotionTags: ["dominant"],
        isGif: true,
        image: "cool1.gif",
        alt: "A corgi looking dominant",
    },
    {
        emotionTags: ["dominant"],
        isGif: true,
        image: "cool2.gif",
        alt: "A corgi looking dominant",
    },
    {
        emotionTags: ["dominant"],
        isGif: true,
        image: "cool3.gif",
        alt: "A corgi looking dominant",
    },
    {
        emotionTags: ["happy"],
        isGif: true,
        image: "excited.gif",
        alt: "A corgi looking happy",
    },
    {
        emotionTags: ["happy"],
        isGif: true,
        image: "excited1.gif",
        alt: "A corgi looking happy",
    },
    {
        emotionTags: ["happy"],
        isGif: true,
        image: "happy.gif",
        alt: "A corgi looking happy",
    },
    {
        emotionTags: ["hungry"],
        isGif: true,
        image: "hungry.gif",
        alt: "A corgi looking hungry",
    },
    {
        emotionTags: ["hungry"],
        isGif: false,
        image: "hungry.jpeg",
        alt: "A corgi looking hungry",
    },
    {
        emotionTags: ["hungry"],
        isGif: false,
        image: "hungry.jpg",
        alt: "A corgi looking hungry",
    },
    {
        emotionTags: ["hungry"],
        isGif: true,
        image: "hungry1.gif",
        alt: "A corgi looking hungry",
    },
    {
        emotionTags: ["insomniac"],
        isGif: true,
        image: "insomniac.gif",
        alt: "A corgi looking insomniac",
    },
    {
        emotionTags: ["insomniac"],
        isGif: true,
        image: "lazy.gif",
        alt: "A corgi looking insomniac",
    },
    {
        emotionTags: ["sad"],
        isGif: true,
        image: "lonely.gif",
        alt: "A corgi looking sad",
    },
    {
        emotionTags: ["sad"],
        isGif: true,
        image: "sad.gif",
        alt: "A corgi looking sad",
    },
    {
        emotionTags: ["relaxed", "happy"],
        isGif: true,
        image: "relaxed.gif",
        alt: "A corgi looking relaxed",
    },
    {
        emotionTags: ["relaxed"],
        isGif: false,
        image: "relaxed.jpg",
        alt: "A corgi looking relaxed",
    },
    {
        emotionTags: ["scared"],
        isGif: true,
        image: "scared.gif",
        alt: "A corgi looking scared",
    },
    {
        emotionTags: ["scared"],
        isGif: false,
        image: "scared.jpg",
        alt: "A corgi looking scared",
    },
    {
        emotionTags: ["scared", "sad"],
        isGif: true,
        image: "scared1.gif",
        alt: "A corgi looking scared",
    },
    {
        emotionTags: ["insomniac", "relaxed"],
        isGif: true,
        image: "tired.gif",
        alt: "A corgi looking insomniac",
    },
    {
        emotionTags: ["insomniac", "relaxed"],
        isGif: true,
        image: "tired1.gif",
        alt: "A corgi looking insomniac",
    },
    {
        emotionTags: ["moody"],
        isGif: false,
        image: "moody.jpg",
        alt: "A corgi looking moody",
    },
    {
        emotionTags: ["sad"],
        isGif: false,
        image: "sad.jpg",
        alt: "A corgi looking sad",
    },
    {
        emotionTags: ["sad", "hungry"],
        isGif: false,
        image: "sad1.jpg",
        alt: "A corgi looking sad",
    },
    {
        emotionTags: ["relaxed"],
        isGif: true,
        image: "relaxed1.gif",
        alt: "A corgi looking relaxed",
    },
    {
        emotionTags: ["insomniac"],
        isGif: true,
        image: "insomniac1.gif",
        alt: "A corgi looking insomniac",
    },
]